name: psychProbing_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - tqdm
  - matplotlib
  - seaborn
  - scipy
  - jupyter
  - nltk
  - openpyxl
  - scikit-learn=1.2.0
  - osfclient
  - adjusttext
  - pip
  - pip:
      - "scikit-learn==1.2.0"
      - transformers
      - torch
      - accelerate
      - "hypertools==0.8.0"
      - jsonpickle