name: psychProbing_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - tqdm
  - scikit-learn=1.2.0 # pinned version to deal with needs_proba break
  - matplotlib
  - seaborn
  - scipy
  - osfclient
  - jupyter
  - adjusttext
  - nltk
  - openpyxl
  - transformers
  - pip
  - pip:
      - hypertools
      - torch
      - jsonpickle
