name: psychProbing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - tqdm
  - scikit-learn=1.2.0
  - matplotlib
  - seaborn
  - scipy
  - osfclient
  - jupyter
  - pip
  - pip:
      - hypertools
      - torch
      - jsonpickle
